// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://dh473z3pprduxbcs3qxpeomtpi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rlipemzt2jg4pcz3glpsr7yr4q",
    "aws_content_delivery_bucket": "nightjarapp1",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://nightjarapp1.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
